#directory to be synced with remote server
directory: build/

#DEVELOPMENT
dev:
  host:
  username:
  password:
  port: 21

  #destination folder on the remote server
  path: /

  #files you wish to ignore when uploading to the remote server.
  ignore_files: false

#PRODUCTION
prod:
  host:
  username:
  password:
  port: 21

  #destination folder on the remote server
  path: /

  #files you wish to ignore when uploading to the remote server.
  ignore_files:
      - .htaccess